accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "0BSD",
    "Zlib",
    "Unlicense",
]

targets = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "aarch64-linux-android",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
private = { ignore = true }
workarounds = ["ring", "rustls", "rustix"]
