[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C", "link-arg=--target=aarch64-unknown-linux-musl",
    "-C", "link-arg=-fuse-ld=lld",
]

[env]
CC_aarch64_unknown_linux_musl = "clang"
CFLAGS_aarch64_unknown_linux_musl = "--target=aarch64-unknown-linux-musl"
